### ISSUE TITLE
Landscape mode on mobile devices sometimes ends up with the wrong @media setting

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1054]
Reported by @chrisgarrity:

> Some additional testing on Samsung 7-inch Android tablet:
In portrait mode: 
> - single column
> - modal fills screen
> - x works to close modal

> Landscape mode:
> - two columns (but tiles are ordered for 3 columns ): )
> - modal extends off the bottom
> - scrolling moves the page behind the modal, modal does not scroll
> - touching outside the modal does close it (although it fills enough of the screen it's hard to touch outside)

**Comment by chrisgarrity** [comment]
I just renamed because this seems like it may be a more general problem with landscape mode on mobile. The event banner on the splash page should be setting the width based on the columns, but didn't shrink when I tested it on my Nexus 5X (Android 7.0)
![screenshot_20161130-100030](https://cloud.githubusercontent.com/assets/399209/20811658/90529b78-b7dc-11e6-9bfb-b88a0df76953.png)

It was fine in portrait mode.
