### ISSUE TITLE
Scratch Website Theme

### ISSUE THREAD

**Issue by iiLucky** [LLK/scratch-www#1075]
On the homepage, the site shows the new theme that has been added but on other Scratch pages like profiles or projects, it shows the old theme.

**Comment by liam4** [comment]
Of course! Those pages haven't been migrated.

Basically, this new "theme" isn't *just* a theme, at all. It's a whole new version of all the pages! You can see the code for the new pages [here](https://github.com/LLK/scratch-www/tree/develop/src/views), all that code is – and since all the code is new it takes a lot of time to remake everything. *Especially* because the *backend* needs to be redone, too - that's the API. (It's not open-source but you can experiment it with it [here](https://api.scratch.mit.edu/) and learn more about it [here](https://github.com/LLK/scratch-rest-api/wiki).)

We say when a page has been *completely* updated to use new code that fits with this codebase (and others - e.g. the backend - as described earlier) that it's been "migrated".

The reason the profile and project pages haven't been migrated is because to finish those you'd need a new backend for those projects - and that means updating the old database to a new one, possibly, setting up the new API for that, and so on and so forth.. And *then* you need to get the frontend done, too.

Just some insight. :)

**Comment by rschamp** [comment]
Very well explained @liam4, thanks!
