### ISSUE TITLE
Spacing between Gender options for languages with longer strings looks odd

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1108]
**TL;DR** Cosmetic-only, spacing between Gender options looks weird.

Staging, Firefox 48, Win 7 VM

We now show Male, Female, and Other in languages like Brazilian Portuguese, as of the fix in https://github.com/LLK/scratch-www/pull/1096, but the spacing in between the lines seems too large. @carljbowman, how do you feel about it?

<img width="259" alt="screen shot 2016-12-13 at 11 33 58 am" src="https://cloud.githubusercontent.com/assets/1320456/21149214/cb145418-c128-11e6-996f-74e1c74fb48a.png">

**Comment by mewtaylor** [comment]
One thing to keep in mind is that the spacing right now is designed to be equal between all options, which means more spacing is required on account of the input field needing to be there (pending fix of the new line thing)

**Comment by carljbowman** [comment]
Once the radio button and the text input at vertically aligned, the addtional space is to be expected. 

As @mewtaylor described, because the input is taller than the label (e.g. 'Masculino') text size and we use a fixed amount of marge on these elements the space between here will be slightly larger.

**Comment by mewtaylor** [comment]
Closing this as expected, since the alignment for the input is fixed in https://github.com/LLK/scratch-www/pull/1111, thanks!
