### ISSUE TITLE
Redirect old cards page to new cards page

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#1114]
https://scratch.mit.edu/help/cards/ 

should redirect to: 

https://scratch.mit.edu/info/cards

**Comment by mewtaylor** [comment]
@kaschm thoughts on simply removing the old endpoint instead?

**Comment by kaschm** [comment]
@ntlrsk do you think that many people have this link out there in the world? if so, we can redirect. otherwise, we can remove the endpoint.

**Comment by ntlrsk** [comment]
The old link is what Google is pointing to as its first entry for a long time now (apparently), and I think educators may have bookmarked it, so I think it's best to redirect and would put this at high priority because the Scratch Coding Cards are receiving publicity. Does that make sense? 

Or, if we just deleted the page, how long does it take Google to correct? 

![image](https://cloud.githubusercontent.com/assets/4721032/21613910/5681affa-d1a5-11e6-93dd-160d9b5f800b.png)

**Comment by kaschm** [comment]
Thanks @ntlrsk - let's redirect the page instead of removing the endpoint. High Google rankings may also indicate that there are a lot of pages linking to that URL elsewhere on the web. Thanks.

**Comment by ntlrsk** [comment]
OK, thanks! It would be great to get this out in this release, because now when people search for the new cards and click the first link, they won't find them.

**Comment by mewtaylor** [comment]
@ntlrsk @kaschm just fyi search would likely take no more than 2 weeks to update.
