### ISSUE TITLE
Japanese characters on title changes location of the project author

### ISSUE THREAD

**Issue by WorldLanguages** [LLK/scratch-www#1191]
![image](https://cloud.githubusercontent.com/assets/17484114/23068276/cda5bdf4-f501-11e6-9fbd-27a3a715e48a.png)

This is probably not very important but, for some reason (probably the chinese characters), the part of the page saying the user who created the first project is located a bit below than the other users

I'm not sure if this is a bug but I will just leave this here.

**Comment by chrisgarrity** [comment]
@WorldLanguages Thanks for pointing this out. It's definitely due to the Japanese characters in the title - they're increasing the height of the line by 4 pixels. It's probably not a high priority, but we could fix it by setting the line height css to something like 1.2em instead of letting it default.

**Comment by TheGrits** [comment]
@chrisgarrity Would the solution you mentioned be the preferred solution?

**Comment by chrisgarrity** [comment]
@TheGrits Yes, that's probably the preferred solution - setting a height, but keeping it relative to the text size not absolute pixels.
