### ISSUE TITLE
Add sort scheme dropdown to search results page

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#1252]
On the explore page, there is a dropdown for the sorting scheme ("Trending", "Popular", "Recent"). This component should be added to the search results page, defaulting to "Popular".  Changing the choice should change the sort order of the results.

The same design on the Explore page should be used for the dropdown, except that the tags should not appear in the row.

**Comment by mewtaylor** [comment]
@St19Galla if you have any interest in this one, it'd be very helpful! Feel free to let me know if you are :).

**Comment by St19Galla** [comment]
@mewtaylor I can certainly give it a try! :)

**Comment by mewtaylor** [comment]
@St19Galla currently the search page just sorts results by the mode `popular` (see [here](https://github.com/LLK/scratch-www/blob/develop/src/views/search/search.jsx#L68)), whereas there is a dropdown in explore. What we'd be looking for is to add the dropdown like [on explore](https://github.com/LLK/scratch-www/blob/develop/src/views/explore/explore.jsx#L158-L167).

The results on both pages are the result of an api call. On search, the api call results (returned in the form of JSON) are then added to the state value `this.state.loaded`. A starting point would be to try and add the dropdown as it is in explore to the page. That `Form` component, you'll see, has a property called `onChange` on it – this means that if you create a function, and set the `onChange` property equal to that function, the function will then get called every time the dropdown is changed to a new value (see [formsy-react](https://github.com/christianalfoni/formsy-react/blob/master/API.md#onchange) for more background). 

The idea would be to have the function referenced by `onChange` make another [call to the api](https://github.com/LLK/scratch-www/blob/develop/src/views/search/search.jsx#L63-L70), and just change the value of `mode` to be whatever is on the dropdown, rather than just `popular` every time. Then, you could get the results, and put them in `this.state.loaded`.

Definitely let me know if you run into any other questions too!

**Comment by kyleplo** [comment]
@mewtaylor I've submitted a PR for this.
