### ISSUE TITLE
FAQ: question about privacy is US-centric

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1282]
The question/answer about privacy `Is Scratch 2.0 (online version) compliant with local and federal data privacy laws?` is specific to the US, but doesn't say that. So it's difficult to localize - should it be translated as is? Should the translator add "United States" to the string? Should translators just ignore it?

Or do we need to update the question so it makes sense for both US and non-US schools. e.g. we care about privacy and comply with US rules, perhaps not other countries if they have stricter standards than US.

**Comment by rschamp** [comment]
@kaschm What do you think?

**Comment by kaschm** [comment]
Really good point. Let's add something to the question, so that if translated it still makes sense. We can handle the larger question of non-US privacy law later. 

Here's the suggested change to the text:

Is Scratch 2.0 (online version) compliant with **United States** local and federal data privacy laws?

Scratch cares deeply about the privacy of students and of all individuals who use our platform. We have in place physical and electronic procedures to protect the information we collect on the Scratch website. Although we are not in a position to offer contractual guarantees with each entity that uses our free educational product, we are in compliance with all **United States** federal laws that are applicable to MIT, a 501(c)(3) organization and the entity that created and maintains Scratch. We encourage you to read the Scratch Privacy Policy for more information.

There are two places in which this question appears:
https://scratch.mit.edu/educators/faq
https://scratch.mit.edu/info/faq

**Comment by St19Galla** [comment]
@rschamp I can take this one if so ^^ :)

**Comment by rschamp** [comment]
@kaschm Sounds good to me!
@St19Galla Go for it!
