### ISSUE TITLE
Credits Page: Reduce work for translators

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#1435]
On the credits page, I see huge parts of the text that doesn't need to be translated: Many, many names! However, it still needs to be "translated" via transifex for any changes to be visible! 
So - isn't it possible to store all the names (as far as possible) seperately and to just translate the normal text? 
Updates would be visible more quickly, and it saves translators redundant copy-pasting!

**Comment by chrisgarrity** [comment]
We agree! As much as possible we should replace lists of names that contain 'and' with just a comma separated list of names that doesn't need to be translated. We'll need to reword some of the text to accommodate that.

Suggested re-wording....

**Previous Scratch Team Members**

Many important contributions have been made by previous Scratch Team members, including John Maloney (who led software development for the first decade of Scratch) and Andrés Monroy-Hernández (who led the development of the first Scratch community website). Other contributors include:

Other names as a comma separated list without 'and' (no translation)

**Acknowledgements**
The following people have also contributed to the development and support of Scratch over the years: 

List of names (no translation)

With the help of [Scratch Translators](http://wiki.scratch.mit.edu/wiki/Translators) around the world, Scratch is available in many languages. 

Note: I'd like to have the list of translators come automatically from Transifex instead of trying to maintain a list manually, but that doesn't seem to be possible currently.

**Supporting Organizations**
Change each list of organizations to just a comma separated list without 'and'. 

/cc @mresmres @ntlrsk @thisandagain additional thoughts or suggestions?
