### ISSUE TITLE
The Project Draft Button

### ISSUE THREAD

**Issue by VutonDesign** [LLK/scratch-www#1544]
As many of us know, there is a draft button on scratch projects!  That's great however the check box for this feature is a lot higher than the text as seen here:

![capture](https://user-images.githubusercontent.com/26391179/30393075-d0c33d82-98b6-11e7-9a28-3a56939ae746.JPG)

I would just submit a pull request to fix this but can't seem to find the code for this button.

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4829

**Comment by towerofnix** [comment]
Just so you know, @VutonDesign - any pages of the "old style" all have their code in a private repository (LLK/scratchr2 - "Scratch, revision 2"). That's why you couldn't find the code for the draft button - the project page isn't migrated to LLK/scratch-www yet!

Bug reports for issues with scratchr2 (non-migrated) pages are still helpful! Though I imagine lower priority issues might just be delayed until the respective page is migrated to scratch-www (e.g., in the design for the eventually-to-come scratch-www `/projects/` page, they might consider making the checkbox more prominent).

**Comment by VutonDesign** [comment]
@towerofnix Ah, That makes more sense. Thank you! 👍
