### ISSUE TITLE
Filter by > Comment Activity too close to filter dropdown arrow - Messages page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1643]
This is a fairly minor cosmetic issue, but "Comment Activity" gets cut-off (in Chrome, Mac) or squished (in Firefox, Mac) by the filter dropdown menu arrow because it is longer than the other filter names. 

To repro, go to the Messages page and choose "Comment Activity" as your filter type in Firefox or Chrome. (It may happen in other browsers as well, but those are the two I tried. This is on Staging & Production.)

Chrome
<img width="219" alt="screen shot 2017-10-31 at 6 15 18 pm" src="https://user-images.githubusercontent.com/1320456/32251501-aca26cd0-be67-11e7-932e-9cb3a7f48770.png">
Firefox
<img width="252" alt="screen shot 2017-10-31 at 6 11 44 pm" src="https://user-images.githubusercontent.com/1320456/32251502-acb16b72-be67-11e7-8a89-f32d47fa3dcb.png">

**Comment by Voltern** [comment]
The Main Reason Behind This Might mean That The Server

**Comment by Voltern** [comment]
It Is Because The Source Code Is different in both browsers 
Chrome
`<div class="messages-title-filter"><form novalidate="" class="form"><div class="select"><div class="form-group row"><label class="control-label col-sm-3" data-required="false" for="frc-messages.filter--527961147"><!-- react-text: 40 -->Filter by<!-- /react-text --></label><div class="col-sm-9"><select class="form-control" label="Filter by" name="messages.filter" id="frc-messages.filter--527961147"><option value="">All Activity</option><option value="comments">Comment Activity</option><option value="projects">Project Activity</option><option value="studios">Studio Activity</option><option value="forums">Forum Activity</option></select><span class="help-block">Not Required</span></div></div></div></form></div>`

**Comment by TheGrits** [comment]
@jwzimmer What would be the preferred behaviour? Should the form width fit the longest string from the beginning or should it change the width based on the currently displayed string?

**Comment by jwzimmer** [comment]
@TheGrits I would think if there's enough real estate, then fitting the longest string would be better than having it change size, but let's see what @carljbowman thinks it should look like. Thanks!

**Comment by vutondesign** [comment]
Strangely enough, I've just fired up Internet Explorer 11 (Windows 8.1) and I don't seem to have the same problem...

![2](https://user-images.githubusercontent.com/26391179/34071974-230c2eaa-e277-11e7-89c4-847e4dd2954c.JPG)

**Comment by GreenBayRules** [comment]
@vutondesign Only pops up like that with comment activity:
![image](https://user-images.githubusercontent.com/11379161/34072053-6093699c-e235-11e7-8156-59ae194c5890.png)

**Comment by vutondesign** [comment]
Oops, misread the first message 😆
