### ISSUE TITLE
Scratch Conference Website - 2 text changes

### ISSUE THREAD

**Issue by me-win** [LLK/scratch-www#1746]
We need a couple of edits made to the text on the Scratch Conference website (scratch.mit.edu/conference). 

1) At the end of the second paragraph ("peer-to-peer discussion and collaboration."), please add the following sentence:

"The conference is intended primarily for adults who support young people learning Scratch."

2) Below the When and Where in the top portion, please add the following sentence:

"Registration opens March 1, 2018." 

Thank you!

**Comment by redmangospros** [comment]
I got this! 👍

**Comment by redmangospros** [comment]
where is the source code?

**Comment by thisandagain** [comment]
@redmangospros https://github.com/LLK/scratch-www/tree/develop/src/views/conference/2018/index

**Comment by redmangospros** [comment]
What do i add inhttps://github.com/LLK/scratch-www/blob/develop/src/views/conference/2018/index/l10n.json to add

- "The conference is intended primarily for adults who support young people learning Scratch."
and 
- "Registration opens March 1, 2018."

**Comment by GreenBayRules** [comment]
In case redmango can't do it, I'll take it ;)

**Comment by redmangospros** [comment]
Nice To Know. Can AYone answer me

**Comment by thisandagain** [comment]
@redmangospros 

For the first item you want to add `The conference is intended primarily for adults who support young people learning Scratch.` to the end of this line:
https://github.com/LLK/scratch-www/blob/develop/src/views/conference/2018/index/l10n.json#L13

For the second item you will need to add a new section to the JSX file and a new corresponding section to the `l10n` file with the `Registration opens March 1, 2018.` text.

For both of these you will need to run this repo locally and test everything prior to making a PR (`npm start` and `npm test`). If you feel confident doing all of that in the next day or so you are more than welcome to do this, but otherwise I would recommend you get a local development environment setup before attempting to take on issues like this. Thanks!

**Comment by redmangospros** [comment]
yeah i know, like in some places it says, date, what name will i keep

**Comment by redmangospros** [comment]
i need help with the jsx file

**Comment by GreenBayRules** [comment]
I made it, but I still need to test it, I'll submit a PR soon.

**Comment by mewtaylor** [comment]
Implemented in #1748
