### ISSUE TITLE
Update Scratch Credits Page

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-www#1769]
Request to add SFE (Siegel Family Endowment) to the list of supporting organizations

**Current Text:**
Supporting Organizations
National Science Foundation, Scratch Foundation, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, MacArthur Foundation.

**New Text:**
Supporting Organizations
National Science Foundation, Scratch Foundation, Siegel Family Endowment, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, MacArthur Foundation.

Link: http://www.siegelendowment.org/

**Comment by vutondesign** [comment]
Was this not fixed in #1714?

**Comment by redmangospros** [comment]
i can tk this

**Comment by ChampikaF** [comment]
Sorry, this is for https://scratch.mit.edu/info/credits

#1714 was for https://scratch.mit.edu/about

**Comment by redmangospros** [comment]
hi

**Comment by thisandagain** [comment]
@redmangospros Please only take this if you can implement, fully test this locally, and submit a PR that includes a screenshot. Can you confirm that you can do this?

**Comment by redmangospros** [comment]
Sure, how do i test though, i forgert

**Comment by thisandagain** [comment]
@redmangospros You will need to run the application locally using `npm start` and also run the test suite using `npm test`.

**Comment by redmangospros** [comment]
so npm start Pull rquest #

**Comment by redmangospros** [comment]
Where is the source code?

**Comment by St19Galla** [comment]
@redmangospros Hello! Here is a link to the source code for this particular issue: https://github.com/LLK/scratch-www/blob/900207da2da7e4b1371fa18ac91e28aff087a222/src/views/credits/credits.jsx#L257-L266

For the future, there are a couple tricks you can try to remember to find things by yourself :) For example, there are two things you might be looking for the code for: components, or pages (views). A component are things that can be re-used on multiple pages, like the flex-row code or the footer! A page is exactly what you think, any webpage from scratch. Both of these places, pages and components, are in the same folder: `src`. Once you click into the `src`, you will be met with 4 folders. Mostly, you'll only care about the first and the last one. The first one is the `components` folder, filled with the things that can be re-used on multiple pages I was walking about. The last one is the `views` folder, which contains the code for most of the webpages from Scratch. For this particular issue, because you are looking to fix something on the Credits page, you will go into the `views` folder. Within it, things get really simple! Each folder is named a descriptive enough name that you should be able to find the one you're looking for easily. For example, in this case, because you are looking for the Credits page code, you should look for the `credits` folder :) Within each folder, there is the .jsx file, which is where the jsx code is that forms the framework of the page; the .scss file, which is where the scss code is that forms the styling of the page; and the .json folder, which is where the magic behind the localization for different languages takes place. Most of the time you'll find the text in the .json file, because the text is able to be translated into different languages there. However, because you are looking to add an organization name, you will go into the .jsx file because we don't need to translate the organization name. From there, just look for the area in the code that you need to change :D I hope this helped! If you happen to have any other questions I suggest taking a look at the Wiki for this repo, which is located [here](https://github.com/LLK/scratch-www/wiki). Or, of course, you can ask anyone here too :)
