### ISSUE TITLE
"About" page is displaying escaped HTML elements in Edible Scratch language

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1772]
I think this needs no further explanation:
![image](https://user-images.githubusercontent.com/28599280/35223481-74c95a44-ffbc-11e7-885f-15d1660ff606.png)

### Steps to Reproduce

Navigate to https://scratch.mit.edu/about with interface language set to Edible Scratch.

### Operating System and Browser

Latest Chrome and Windows 10

**Comment by thisandagain** [comment]
I can't replicate this @Kenny2github. Can you post a screenshot from an incognito window with all browser extensions disabled?

**Comment by thisandagain** [comment]
@Kenny2github Hmm. What happens if you clear your cache?

**Comment by Kenny2github** [comment]
Ahhhh! It's an Edible Scratch problem! My default interface language is Edible Scratch and this doesn't happen in English.

**Comment by thisandagain** [comment]
Good detective work! Thanks @Kenny2github!

**Comment by thisandagain** [comment]
@chrisgarrity Can you look into this?

**Comment by Kenny2github** [comment]
Note: The same thing happens with Meow.

**Comment by chrisgarrity** [comment]
@Kenny2github this is due to removing `FormattedHTMLMessage` and adding placeholders in the translation string in https://github.com/LLK/scratch-www/pull/1714, and https://github.com/LLK/scratch-www/pull/1757

Meow and Edible Scratch aren't in transifex, so they have to be manually updated. Would you be interested in updating them in the scratchr2_translations repo: https://github.com/LLK/scratchr2_translations/issues/10

Thanks for catching this!

/cc @thisandagain

**Comment by chrisgarrity** [comment]
Tracking in https://github.com/LLK/scratchr2_translations/issues/10
