### ISSUE TITLE
Update Scratch Conference site (for February 6)

### ISSUE THREAD

**Issue by me-win** [LLK/scratch-www#1782]
Hi, requesting a new round of updates to scratch.mit.edu/conference. These edits must appear on **February 6, 2018.**

All text updates can be found in this document: https://docs.google.com/document/d/1oJGcmMnyTkp5C6d1l6lhi_ies9HmsyZBjZk_mhtGTcw/edit?usp=sharing)

We're working toward the template seen below:

![scratch-conference-update](https://user-images.githubusercontent.com/33295461/35289037-43256faa-0034-11e8-86cc-6dddd143c47e.png)

* Swap the existing header photo with the photo attached (DSC4478)

* Update the header image with text overlay(as seen in the image), reading: 
Scratch Conference 2018:
The Next Generation
July 26-28, 2018 | Cambridge, MA, USA

Registration opens March 1. 

* Move the conference date and location to the right sidebar (as seen in the attached template)

* Remove the section and button link to submit proposals (begins "Interested in offering a session?")

* Move the "Registration" section up

* Add the following sentence in bold under "Standard Registration (after May 1): $300": **Registration opens on March 1, 2018.**

* Add "Questions" section. Text can be found in this doc): https://docs.google.com/document/d/1oJGcmMnyTkp5C6d1l6lhi_ies9HmsyZBjZk_mhtGTcw/edit?usp=sharing

![rez_dsc4478](https://user-images.githubusercontent.com/33295461/35416522-59f703fa-01f7-11e8-8215-06ffe117f8c0.jpg)

Thank you!

**Comment by Narulacodes** [comment]
I can take this!

**Comment by thisandagain** [comment]
@Narulacodes We'll handle this internally due to the strict timeline.

**Comment by Narulacodes** [comment]
I can do this before the 5th

**Comment by chrisgarrity** [comment]
@me-win I have a few questions.
1. Can the text in the banner be `Registration opens March 1, 2018.` including the year because we already have that text for translators. 
2. Could the **When** text be 'July 26, 2018 - July 28, 2018' instead of 'July 26-28, 2018'? Again, if we use the longer form it's automatically translated, otherwise it's a new string that we have to get translated.
3. The mockup shows a new logo image - do you have the image? For now it's just the Scratch logo followed by the word Conference.
4. The current second paragraph includes the sentence: `The conference is intended primarily for adults who support young people learning Scratch.` - do you want it removed?

/cc @ChampikaF

**Comment by me-win** [comment]
1. Yes, totally fine.
2. Yes!
3. I don't think we're using the Scratch Conference logo anymore, so keeping it the Scratch logo and the word Conference is fine. (See the full site mockup here: https://scratch.mit.edu/conference/2016)
4. That line isn't showing up in my view for some reason. Please keep it. (I'll update the Google Doc). 

Thank you!

**Comment by chrisgarrity** [comment]
Note: proposal submission closes on Feb 5, so these changes should get deployed on Feb 6.
