### ISSUE TITLE
Splash - remove recently shared projects row 

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1860]
We would like to remove the recently shared projects row from the homepage. This row is intended to help newer and undiscovered Scratchers gain visibility in the community. Unfortunately our data shows that it doesn't do that very effectively, and unfortunately it can also be taken advantage of by troll to show inappropriate content.

@chrisgarrity Sorry to add yet another thing to your plate, but this is urgent.
/cc @rschamp @christanbalch @dietbacon

**Comment by towerofnix** [comment]
> and unfortunately it can also be taken advantage of by troll to show inappropriate content.

I'll assume that this has actually happened enough to really make it not worth it? Probably, considering this issue is critical.

Anywho, I'm curious what the recommended way to find recent projects will be with this gone. It looks like maybe it'll be [the Recent section of the Explore page](https://scratch.mit.edu/explore/projects/all/recent).. although I think that that's a bit lacking, since it takes a couple clicks to get to (explore, a subtle button in the toolbar, then the "trending" dropdown, which is impressively *hidden* / not-opaque). I doubt many people use that section of the Explore page much, but I'm not the one with the data - how often are recent projects found from there relative to the front page row?

Sorry to barge into a code-issue with these thoughts; this is probably being discussed somewhere more internally!

**Comment by Barthdry** [comment]
This Featured was removed. Anyway it is fine there was some trolls not always. :|
