### ISSUE TITLE
Scratch search bar preserves URI encoded strings from the URL

### ISSUE THREAD

**Issue by joker314** [LLK/scratch-www#1913]
If a user searches for `cows`, then the resulting page will have the search bar filled in with `cows`, as well as the results below it. It's reminding the user what they typed in the bar, by keeping it on screen alongside the results.

When a user searches for `?`, the query string will contain the URI encoded version of that symbol, `%3F`. This is normal. The Scratch search bar is also filled in with `%3F`, and this is the bug.

Given that the search bar should be showing what the user typed in, this can cause confusion.

### Steps to Reproduce

1. In Scratch's search bar, type `?` and hit enter
2. Observe that the search bar on the resulting page does not contain `?`, it contains `%3F`

### Operating System and Browser

Chrome on Windows 10

**Comment by towerofnix** [comment]
I'm pretty sure this is a duplicate of #1224 - which is a help-wanted issue, so if you want to have a go at that..! :)

The code you'd need to take a look at is probably in [`src/views/search/search.jsx`](https://github.com/LLK/scratch-www/blob/develop/src/views/search/search.jsx) - maybe in the `componentDidMount` function, since that looks like where URI-decoding is (supposed to be) happening?

**Comment by joker314** [comment]
Thanks!
