### ISSUE TITLE
Most of the site footer cut off on mobile. 

### ISSUE THREAD

**Issue by kerrtrvs** [LLK/scratch-www#2101]
When on mobile, only some of the footer is shown. 

![img_0460](https://user-images.githubusercontent.com/26391179/45953470-133c8100-c002-11e8-99e9-70272fa06493.jpg)

### Steps to Reproduce
Visit any scratch-www page on a mobile browser. 

### Operating System and Browser

iOS 12.0 - Safari

**Comment by LiFaytheGoblin** [comment]
I think this is on purpose?

**Comment by kerrtrvs** [comment]
@LiFaytheGoblin Ah right, should I close this then?

**Comment by LiFaytheGoblin** [comment]
@carljbowman do we want to revisit what to put into the mobile footer?

**Comment by Kenny2github** [comment]
This seems to be on purpose. And initially I did the same for the Scratch Wiki's footer but then I realized I could simply change `flex-wrap: nowrap` to `flex-wrap: wrap` and the footer would become really tall (fine for mobile) rather than really wide (not ok for mobile). Consider changing to `flex-wrap: wrap` on the main site?

**Comment by carljbowman** [comment]
This was intentional. The footer would be enormous on mobile if we showed everything. Reducing content or features when scaling down to tablet or mobile is pretty common practice, and one that we will continue. I call this out because I know you are working on the Project page and there will be somethings on the project page that will become hidden as we scale the page to fit smaller devices.

Going to close this issue as we do not plan to make updates to the footer anytime soon.
