### ISSUE TITLE
Using the browser "back" button after opening a 3.0 library doesn't close the library

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2129]
_Describe the problem. Please make sure you can reproduce the bug. It's also
helpful to include screenshots or animated gifs of the problem._

### Steps to Reproduce
_Explain what someone needs to do in order to see what's described above. The 
more detailed and explicit the steps are the better._

1. Open a project in the preview
2. See inside
3. Open a library
4. Hit back in your browser

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
Mac OS 10.13.6 Firefox 61.0.2

**Comment by locness3** [comment]
I thnik this issue is more to be in LLK/scratch-gui

**Comment by benjiwheeler** [comment]
Reproducing is tricky because of the different ways browsers manipulate history. Try:

1. Open a new tab or browser window
2. navigate to one project's page
3. *type or paste* the url of another project's page, hit enter
4. click "See inside"
5. click to open sprites library
6. hit browser back button.

You want to see editor; you actually see project page.
