### ISSUE TITLE
What privileges should admins have in project page/editor? ability to alter anyone's project?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2224]
Question relating to the user capabilities introduced in https://github.com/LLK/scratch-www/pull/2187

**Comment by towerofnix** [comment]
This makes me wonder if there has ever been an instance of a Scratch Team member modifying another user's project.

Semi-relatedly, my understanding is that usually when a project is unshared by the ST because it includes something which is not okay to be shared, the ST sends an alert to the user describing what should be changed before it can be shared again. The ST never makes that change themselves, though - they leave the responsibility to the user.

I think there's a point of privacy and respect to be made here.

Practically, I'm not sure how this would work, either. Frequently an ST member might want to look inside a project and play around with modifying the scripts (just the way any other user might), to see what happens and then potentially create a remix. It would obviously be bad if that playful experimenting modified the original project. So care would have to be taken to prevent that from happening - perhaps by disabling auto-save and adding a "Overwrite original project" option to the File menu.

**Comment by rschamp** [comment]
Moderators do not have the ability to modify the contents of others' projects, just like regular users.
