### ISSUE TITLE
Warn the user when a project uses the “username” block

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2392]
We should show a warning modal to logged in users when a project can record that you have played the project using cloud data.

**Comment by Kenny2github** [comment]
Can we take this opportunity to make the "your username will be recorded" warning a little less forbidding? Currently it goes along the lines of "log out so that they can't tell you were there", and while that's true the wording is kinda scary. Could it instead be "The "username" block is used in this project. If you log out, the value it reports will become blank."

**Comment by thisandagain** [comment]
Just for reference the current warning is:
![image](https://user-images.githubusercontent.com/747641/49532383-5c267680-f88a-11e8-8ed5-38ea3ea2a2df.png)

In my opinion this doesn't seem too stern / forbidding.

**Comment by DeleteThisAcount** [comment]
the project cant _actually_ keep the info of every user that uses it.
