### ISSUE TITLE
The Add to Studio modal makes it look like you can remove a project you don't own from studios you don't curate

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2539]
If you're looking at a project you don't own, and open the Add to Studio modal, all the studios the project is in appear checked off. You can un-check them, as if you're able to remove the project you don't own from studios you don't curate.  The only studios that should appear to be interactive are the ones you can actually take action on.

![image](https://user-images.githubusercontent.com/1512021/50364112-9d7e7d80-053c-11e9-8000-14b986833e69.png)
![image](https://user-images.githubusercontent.com/1512021/50364118-a4a58b80-053c-11e9-944c-00a8f6da01d3.png)

After reload

![image](https://user-images.githubusercontent.com/1512021/50364131-b129e400-053c-11e9-985e-e2be8dc04da8.png)

**Comment by benjiwheeler** [comment]
I don't remember the specific conversation, but I asked if users should be able to remove their projects from a studio that someone else added them to, and was told yes. This was a question in developing the Add to Studio modal UX because we had to face the situation where a user removed their project from such a studio, then wanted to add it back, when the user doesn't have the power to add a project to that studio.

I can try to dig up that conversation, or we can just bring this up for discussion, or @rschamp or @thisandagain could just decide -- should users be able to remove projects from studios where they don't want them included?

**Comment by benjiwheeler** [comment]
@carljbowman @kathymakes Looks like we need design for this:

What should the Add to Studio modal look like when the studio memberships are NOT changeable by the user? Should we just disable clicking, but have them look the same? (I'll start working on that as a stopgap.) Or maybe make them a different color?

**Comment by benjiwheeler** [comment]
Another consideration is that we might want to just not display studio buttons, if the project is in those studios but the user doesn't have permission to alter that fact.
