### ISSUE TITLE
Add reference to National Science Foundation (NSF) on credits page

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#2541]
## Problem
We would like to make sure that the NSF is given credit for it's support of Scratch throughout it's early history even though the NSF is not a "current" sponsor. 

## Proposed Solution
Add a section for "Past Sponsors" that includes the NSF

/cc @kathymakes @carljbowman @ntlrsk

**Comment by Kenny2github** [comment]
help wanted or no?

**Comment by thisandagain** [comment]
@Kenny2github We'll need to discuss and come up with copy and a design first.

**Comment by ntlrsk** [comment]
Here is some possible wording, drafted with @mresmres 
Heading: **Initial Research Funding**
with just the National Science Foundation logo
or we could write a sentence including the grant numbers, depending on the design of the page.

**Comment by thisandagain** [comment]
@kathymakes Would you mind putting together a mockup with this change?

**Comment by kathymakes** [comment]
@thisandagain Just seeing this, I can definitely do that today :) Thanks.

**Comment by kathymakes** [comment]
I was thinking we could have it just as text, with no logo, and link to the NSF website.
It's a more modular section this way without a logo, and still contains a link for more info.

<img width="533" alt="screen shot 2019-01-09 at 2 59 22 pm" src="https://user-images.githubusercontent.com/8203939/50925430-49bad200-1420-11e9-8dbb-b8fad9595cb2.png">

If we feel good about this direction + copy I can make an issue at add @picklesrus to it! 

(Alternatively we could put a logo in the Sponsors section, but this feels more misleading because they're a past, not current, sponsor.)
<img width="568" alt="screen shot 2019-01-09 at 2 59 17 pm" src="https://user-images.githubusercontent.com/8203939/50925488-77078000-1420-11e9-8823-e202f7ee3470.png">

**Comment by kathymakes** [comment]
Actually, it feels better to me to put it with "Past contributors," and together with the sections that feel more past tense (and reference the NSF grant.) What do folks think of this ordering - any other suggestions? 
@ntlrsk @thisandagain 

<img width="733" alt="screen shot 2019-01-09 at 3 15 18 pm" src="https://user-images.githubusercontent.com/8203939/50925968-d74af180-1421-11e9-9de1-e7dcc727999e.png">

**Comment by thisandagain** [comment]
Thanks @kathymakes. A big part of our reasoning for adding the NSF is that is validates our research origin story, so my leaning is towards the your second sketch:
https://user-images.githubusercontent.com/8203939/50925488-77078000-1420-11e9-8823-e202f7ee3470.png

**Comment by thisandagain** [comment]
Closing pending larger changes to the credits and about pages.
