### ISSUE TITLE
404 page writes URL as url

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-www#2572]
_Describe the problem._
Instead of using URL because it is technically not a word, the 404 page uses url.

### Steps to Reproduce

Visit a page that 404s

Example: https://scratch.mit.edu/projects/1
Example: https://scratch.mit.edu/404

### Operating System and Browser

any works but I'm on Chrome Windows 10

**Comment by joker314** [comment]
The human-friendly error message displayed to a Scratch user when they navigate to a 404 URL uses the term "url".

However, because URL is an abbreviation, its letters should all be capital letters. The bug being reported is the case of the letters is non-standard (lowercase not uppercase). @thisandagain

**Comment by DeleteThisAcount** [comment]
@thisandagain @joker314 explains it very well

**Comment by thisandagain** [comment]
@joker314 Ah! I see now. Thanks.
