### ISSUE TITLE
Remix Credit Avatars are not square

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-www#2592]
The avatar should maintain a square ratio. Below are two examples of the issue:

Two Remix Credits
<img width="476" alt="screen shot 2019-01-03 at 4 20 29 pm" src="https://user-images.githubusercontent.com/3409578/50662315-e5a59300-0f73-11e9-9587-ba7e6ffead66.png">

One Remix Credit
<img width="486" alt="screen shot 2019-01-03 at 4 21 52 pm" src="https://user-images.githubusercontent.com/3409578/50662318-e6d6c000-0f73-11e9-8673-092250c97e78.png">

Also, sometimes avatars initially appear distorted:

![image](https://user-images.githubusercontent.com/3431616/58370637-eb762380-7ed6-11e9-9cd3-e1db2fbd992e.png)

**Comment by IamTregsthedev** [comment]
I can Fix this if Needed? :) 👍

**Comment by JoelGritter** [comment]
This issue appears to be resolved now (example screenshot from https://scratch.mit.edu/projects/664891213/): 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/13542746/159825840-16c9e5a6-df0a-4b39-9379-2e03f14fd33b.png">

@seotts not sure who to ping about this, since you reviewed my past couple PRs thought I'd ping you.
