### ISSUE TITLE
Change video on "About" page to Scratch! video

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#2611]
Change video at the top of About page to the Scratch! video: 
https://scratch.wistia.com/medias/joal01i8b1

**Comment by IamTregsthedev** [comment]
I'll Take this!

**Comment by towerofnix** [comment]
Is there a list of projects that are featured in this video available, by the way? (Maybe a studio containing them?) Besides it seeming that one *has* to credit featured projects because of the Creative Commons license they're under, it would just be nice to check out those projects out of interest.

**Comment by apple502j** [comment]
@towerofnix Yeah... (Scratch Overview both violated BY and SA - no credits, overriding license from BY-SA to BY-NC-SA)

**Comment by ntlrsk** [comment]
@towerofnix @apple502j Thank you for raising this - the video creators on our team are working on adding credits.

**Comment by MasterOfTheTiger** [comment]
@ntlrsk what about the license for the Scratch! video?
