### ISSUE TITLE
Text overflow in project Notes and Credits

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#2853]
Text overflows with really long links:
![image](https://user-images.githubusercontent.com/28599280/54734318-aa614a80-4bd9-11e9-8151-021f4c80c017.png)

### Steps to Reproduce

1. Go to https://scratch.mit.edu/projects/10135908/
2. Observe

### Operating System and Browser

Windows 10 OS Build 17763.437, Chrome 73.0.3683.103

**Comment by Smrman** [comment]
Just add the line 
```css
.project-description {
    word-break: break-word;
}
```
to https://github.com/LLK/scratch-www/blob/develop/src/views/preview/preview.scss#L466

_Before_
![image](https://user-images.githubusercontent.com/17651422/68261294-ec8fad00-003f-11ea-9344-6d772702e183.png)
_After_
![image](https://user-images.githubusercontent.com/17651422/68261262-cff37500-003f-11ea-9675-3e7a992734a9.png)

I agree it might not be the prettiest solution, but at least it works and the layout is fixed...
Also, what are the odds for an user to type a 55+ characters long URL?

**Comment by benjiwheeler** [comment]
Looks like https://github.com/LLK/scratch-www/pull/3599 didn't get it right!

This is https://scratch.mit.edu/projects/361718885/ :
![image](https://user-images.githubusercontent.com/3431616/75998748-4d84a000-5ecf-11ea-8645-d567e68fc5c1.png)

Yikes! Also see ModTools' user verification project, https://scratch.mit.edu/projects/10135908/ :
![image](https://user-images.githubusercontent.com/3431616/75998841-6e4cf580-5ecf-11ea-9890-66340557b69e.png)

The main problem is that we should have used `overflow-wrap: anywhere`
Seems like the right combination to use is actually:

```
overflow-wrap: anywhere;
word-break: keep-all;
```

Adding those, the problem seems fixed:

![image](https://user-images.githubusercontent.com/3431616/75999479-44e09980-5ed0-11ea-8326-17436a324ec9.png)

![image](https://user-images.githubusercontent.com/3431616/75999502-4c07a780-5ed0-11ea-9fc0-842e4ab65f39.png)

## Why `keep-all`?

`keep-all` is better than `normal` (or just omitting `word-break:` because it handles Chinese and other Asian languages better. With `normal`:

![image](https://user-images.githubusercontent.com/3431616/75999299-04811b80-5ed0-11ea-98cd-e6ce57e6c7ca.png)

With `keep-all`:

![image](https://user-images.githubusercontent.com/3431616/75999311-08ad3900-5ed0-11ea-9082-88294ff9990b.png)


![image](https://user-images.githubusercontent.com/3431616/75999029-ace2b000-5ecf-11ea-853f-a805f0a8b5b6.png)

**Comment by benjiwheeler** [comment]
For anyone trying to work on this:

You'll want to:
1. Find the same place in the code we edited in https://github.com/LLK/scratch-www/pull/3599/files
2. Instead of `overflow-wrap: break-word;`, put: 
```
overflow-wrap: anywhere;
word-break: keep-all;
```
3. Test pages that overflow now, like https://scratch.mit.edu/projects/361718885/ and https://scratch.mit.edu/projects/10135908/ on various browsers -- or ask for help testing them

**Comment by apple502j** [comment]
@benjiwheeler Did you check the compat data? You need to bump supported versions and drop Safari support.

**Comment by benjiwheeler** [comment]
@apple502j I did not check that! Hm, you're right, my proposed fix doesn't seem to work on Safari. I wonder how others are solving that problem...
