### ISSUE TITLE
Replication lag can prevent new user from appearing to be logged in, including a new student

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#3539]
In Join Flow, replication lag can prevent new user from appearing to be logged in.

This is a problem with both the existing Join Flow, and the new Join Flow launching in November 2019.

One proposed partial solution is to have the new Join Flow, after hearing back that the user was registered, repeatedly retry refreshing the session until it sees the logged in sessionid for the user; only after seeing this should it show the user the final, "Welcome" step.

**Comment by jakel181** [comment]
I have experienced this issue while creating student accounts from a student sign up class registration link from a teacher. When I clicked "next step" on the second step nothing happen and I clicked "next step" again and it said that "this username has already been taken" I proceed to try to make two more accounts without know it was actually creating the accounts, thinking that each username I tried to use was already taken. It wasn't until after the third time and checked, and saw the account were being created.

**Comment by benjiwheeler** [comment]
@jakel181 Thanks so much for bringing this to our attention.

So to make sure I understand you, are you saying that this happens:

1. the teacher creates a registration link and gives it to the class
1. a student goes to that URL, and chooses a username and password
1. the student clicks "next step" and it seems like nothing happens
1. the student clicks "next step" again, and it says "this username has already been taken"

Does that match what you're seeing?

**Comment by jakel181** [comment]
Yes sir! It happens when you click "next step" on the personal information page.
So it's more like this:
1.The teacher creates a registration link and gives it to the class
2. a student goes to that URL, and chooses a username and password
3. The student clicks "next step" and moves on to the personal information page
4. the student fills out the forum with birth month, year etc.
5. the student clicks "next step" and it seems like nothing happens
6. the student clicks "next step" again, and it says "this username has already been taken"

**Comment by benjiwheeler** [comment]
It would be good to confirm that this issue has been fixed by #3640.
