### ISSUE TITLE
Migrate - Cards

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#372]
https://scratch.mit.edu/info/cards/

Related #362

**Comment by thisandagain** [comment]
@mewtaylor Could you take this and #362 ?

**Comment by liam4** [comment]
On the topic of cards, why are images being used for "view card" and "get all the cards"?

**Comment by mewtaylor** [comment]
@liam4 are you referring to the pdf icon to the left of the link?

**Comment by liam4** [comment]
No, I was talking about the text..

Oh, haha, oops! Sorry, Firefox is weird in making the text act like an image.

Curious now though why the font "scratch-icons" renders as Times (I think)? That doesn't really fit with the style of the rest of the site..

**Comment by mewtaylor** [comment]
@thisandagain @rschamp here's a proposal for how we might handle localizing links to static assets, at least as a short term solution while we work out which localization tool we use long term:
* use the `formattedMessage` system build into react-intl to handle the actual string to be placed in the anchor
* create a separate file in the views dir called `l10n-static.json` that contains the urls to be localized
* add a global config json file that contains, for each language, the localized versions of static urls for each language that has them. This would require being updated whenever we get new localized pdfs/assets, which is not ideal, but I think is fine for the short term since we don't get new pdfs/assets that often.
* use the `build-locales` script (during the `make translations` step) to add localized urls to the `{{view}}.intl.js` bundle for a given view. This will iterate over `l10n-static.json` files, and check in the global config file to see if a locale has the localized version of a file. If it doesn't, it'll default to english as it does currently

Your thoughts would be greatly appreciated!

**Comment by rschamp** [comment]
That sounds like a good strategy to me.

**Comment by mewtaylor** [comment]
@carljbowman I made some tiny tweaks to the design of the page – thoughts?
![cards](https://cloud.githubusercontent.com/assets/1815772/13791490/c73f3fe2-eac3-11e5-88c0-4def0b2338e1.png)

**Comment by carljbowman** [comment]
@mewtaylor - This looks great! I do have two tiny details. 

1. If possible we should use the typography from our global type sheet: `_typorgraphy.scss`. That intro section gets a little lost with all the photos. There is a class paragraph style called `.intro` for these types of mastheads. 

2. Not sure about reusing the card icon from the HOC page next to 'View Card'. It is not really mean't for the size and details get a bit lost. Also that particular icons has a download arrow. I could provide a PDF icon to go next to 'View Card' or I could provide a better sized download icon and we could change the text to 'Download Card'.

**Comment by mewtaylor** [comment]
@carljbowman thanks so much! For the icon – I'm happy with whichever way you think is best. I can bring over the pdf icon that we have in scratchr2, or one of us can grab one, whichever you'd prefer.

**Comment by thisandagain** [comment]
@mewtaylor can this be closed?

**Comment by mewtaylor** [comment]
Yes – sorry I thought the PR closed it. Thanks!
