### ISSUE TITLE
download.iconAltText is missing from l10n.json

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#3802]
iconAltText is used at https://github.com/LLK/scratch-www/blob/develop/src/views/download/download.jsx#L48 but not defined in https://github.com/LLK/scratch-www/blob/develop/src/views/download/l10n.json

**Comment by BryceLTaylor** [comment]
@apple502j Can you please describe the issue as it appears to the user and steps for how you can see it?

**Comment by apple502j** [comment]
Why do I need "repro" when source code tells so?

Anyway this is both dev facing and accessibility problem - screen readers would speak "download dot icon alt text" (because its alt is `download.iconAltText`) and developers get "translation not found" message on console.

**Comment by rschamp** [comment]
Hi @apple502j — while we can investigate and figure out what behavior each issue will cause, it's important to be able to tell from the description in GitHub what the end-user experience is for a particular bug so that we know how to prioritize it without investigating.  We are a small team and there are many issues reported.

I would add that if the download icon does not load, the alt text is displayed as "download.iconAltText" instead of a descriptive message.

**Comment by benjiwheeler** [comment]
Seems like the fix is straightforward: add a string with the key 'download.iconAltText' and value 'download' to https://github.com/LLK/scratch-www/blob/develop/src/views/download/l10n.json .
