### ISSUE TITLE
Splash header needs a default state

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#396]
Currently, once the browser loads a page, that page then makes a request to the api to see if the user who's loading the page is logged in or not. While the page is waiting for the api to make a response, the nav defaults to its signed out state – it shows the `intro` component, which is what is displayed when a user is logged out.

This is usually not noticeable, as often the api responds quickly with information about whether the user is logged in. However, this can still be confusing for users. It might briefly appear to them that they are logged out – prompting them to try and login – when in reality, the page is still trying to determine if they are or not.

We need the splash view to have a "default" state – a design for before it knows whether or not the user is logged in.

**Comment by Radical-from-Scratch** [comment]
In my opinion, checking to see if logged in or not should be before even the first line of HTML. I always had a suspicion  that this would happen, and it also has a more notable difference on the site then you'd think.

**Comment by thisandagain** [comment]
/cc @carljbowman 

I think there are a couple parts to this. First, I agree we need to design an explicit "empty" state prior to the navigation being rendered. In some ways, this is really a UI design issue. If we had a little more consistent UI in terms of scale / segmentation between logged-in and logged-out, the design of the empty state could look much more natural rather than adding visual complexity for a split second during page load (which would likely just make the problem worse). Without this, I think we likely have enough information about the user to "do the right thing" on subsequent page loads after we have already performed a session check. This could influence what the default state looks like as to help avoid the visual "jar" that happens today by optimizing for the 90%+ case of a user continuing to be logged in should a session cookie exist.

**Comment by Radical-from-Scratch** [comment]
Ok with me

**Comment by technoboy10** [comment]
Resolved by #539.
