### ISSUE TITLE
QA - Search style regression

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#397]
![image](https://cloud.githubusercontent.com/assets/747641/14084751/51dcbca8-f4ea-11e5-82db-fdd5fabac2a3.png)

Unclear where this style regression was introduced, but appears to be isolated to the splash view. 

/cc @mewtaylor @rschamp @carljbowman

**Comment by mewtaylor** [comment]
This was fixed after a purge all on fastly and a hard refresh.

I wasn't able to repro locally on `release/2.2.7`, but was able to when I edited `navigation.scss` to include https://github.com/LLK/scratch-www/pull/394. I think that PR was the issue, since staging got develop when that was pushed. It appears that `develop` no longer is missing the `&` though, so I believe we're all good.
