### ISSUE TITLE
the video on the front page's link redirects to someone's profile

### ISSUE THREAD

**Issue by JeffaloBob** [LLK/scratch-www#4048]
the introduction to scratch video's bit.ly link at the end redirects to someone's profile
### Steps to Reproduce
1. sign out
2. click video.
3. watch video
4. finish watching video
5. type in bit.ly/scratch3video into your web browser
6. not get to list of videos, but instead visit https://scratch.mit.edu/users/54329/

edit. this is because link is case sensitive

### Operating System and Browser
Windows 10 chrome (It doesn't matter)

This seems like it would require re-rendering the video with a new link that wasn't squatted by a scratcher, or contacting bit.ly (I know that this isn't a scratch-www issue per-say but it's the only place to report it that makes sense)

**Comment by BoomerScratch** [comment]
It did work before...

**Comment by Nambaseking01** [comment]
Well, that's strange...

Seems weird!

**Comment by BoomerScratch** [comment]
It's supposed to redirect to https://scratch.mit.edu/studios/5826815/...

**Comment by JeffaloBob** [comment]
it's because of the capitlization. try it in all caps. and then try it all lowercase

**Comment by BoomerScratch** [comment]
@JeffaloBob So it's http://bit.ly/Scratch3Video... That means that it is not a bug. I think it's ok to close this.

**Comment by JeffaloBob** [comment]
yes, but it's still dangerous because people wouldn't expect it to be case sensitive. perhaps a link should be added directly on the page?

**Comment by GrahamSH-LLK** [comment]
@JeffaloBob Whoever is in charge of the video on the ST could add a CTA (Call to action). Using the instructions [here](https://wistia.com/learn/marketing/customize-your-video-cta)  @BoomerScratch Do you know who is in charge of the videos? Bit.ly most likely won't change the link, and this seems easier.

**Comment by Accio1** [comment]
I would suggest that in the future, the ST doesn't use URL shorteners, because this clearly demonstrates that someone else could claim another version of the link with different capitalization. In this case, the lowercase link leads somewhere harmless (a Scratcher's profile), but someone in the future could make a lowercase link that leads to a malicious site which could expose users to inappropriate content or install malware on their computer. Most people don't know that bit.ly links need to be typed with the exact capitalization that they're listed as, so this could lead to many people typing the incorrect link and going to the wrong site/page. 

This seems like a pretty large security flaw, and I would suggest that the ST removes shortened links from the site in order to prevent Scratchers from being exposed to potentially dangerous content.

**Comment by Accio1** [comment]
@benjiwheeler my comment above lists a pretty severe security risk, so I am tagging you so that it's brought to your attention.

**Comment by JeffaloBob** [comment]
yes i agree accio.

**Comment by GrahamSH-LLK** [comment]
@Accio1 That's why I suggested a Call To Action. That way, they can still use a bit.ly link, but there is less risk as it is a direct link to the bit.ly. I personally use bit.ly links so I can see how many clicks/views I get. (Vs. typical viewers)

**Comment by R4356th** [comment]
So it is supposed to redirect to the official Scratch video tutorials' projects studio made by an account controlled by the ST, LearningResources?

**Comment by Accio1** [comment]
> So it is supposed to redirect to the official Scratch video tutorials' projects studio made by an account controlled by the ST, LearningResources?

Yes, if you type the link in lowercase, it links to https://scratch.mit.edu/users/54329/. This is because bit.ly links are case specific, so bit.ly/scratch3video links somewhere different than bit.ly/Scratch3Video

**Comment by GrahamSH-LLK** [comment]
> Probably Zinnea (no idea about her GitHub username)
The credits page lists her as Zoe, so I'm guessing she is zoebentley.

**Comment by BryceLTaylor** [comment]
This is not a bug with our code, so I'm going to close this issue.  We are discussing this issue as a team.

**Comment by KatzKingdom** [comment]
Hey, I am @54329 (where the link redirects).  I made the bit.ly link a good while ago when I was bored for fun.  Didn't expect this to cause trouble.  Though I'm not certain what my account info is, I could try to change the link.

**Comment by benjiwheeler** [comment]
IIRC, bitly doesn't let you change a link after you've created it because they don't want people to repurpose shortened links in unexpected ways.

I think the main mistake here was creating the link with a capital letter in the first place. We should try to use lowercase letters in links/URLs at all times!

I do think it would be smart for us too change the link we show at the end of this video.

**Comment by GrahamSH-LLK** [comment]
@benjiwheeler I personally think a CTA would work better. Ie. Imagine someone has caps lock on and doesn't realize, or types with capitals accidentally. Wistia has an article [here](https://wistia.com/learn/marketing/customize-your-video-cta).
