### ISSUE TITLE
Strings not available for translation

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#419]
Some strings still appear in English and don't seem to be available for translators to translate:

- [ ] About page - 'About Scratch' header
- [ ] Title element - definitely on About page, and on others
- [ ] Discuss page - 'Discuss Scratch' header - also, are sub-categories like 'Welcome to Scratch' possible to translate?

I checked this in Portuguese (BR) and it had all the same issues. So it's not just Norwegian.

**Comment by mewtaylor** [comment]
Hmm – "About Scratch" is marked for translation, and is the same string in both the About page and the footer. It's only not showing up on the page, so there's likely some issue with the build for pages there.

Thanks for the heads up about the title components – I'll think on that one a bit, since it's something that exists outside of react components.

For Discuss – Those strings are stored in the database, so it might be hard to load them into pootle for localization. There's also the question of whether they should be translated – there's no guarantee they will have content that is localized, especially since we have language-specific forums in Discuss as well. Thoughts?
