### ISSUE TITLE
Question: Why is scratchr2 Private

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-www#4206]
I'm sure theirs a perfectly good explanation, but can someone explain?

**Comment by R4356th** [comment]
Here is a qoute from thisandagain-
"Our backend code is private for a number of reasons:

- It is tied very closely to our backend infrastructure which for reasons of scale is fairly large and complex. Because of this, open sourcing our backend code wouldn't just mean publishing `scratch-api` but also nearly 20 other repos that support it (otherwise it would be useless). With that and the scale of our hardware it isn't something that any single engineer could just put on a server and run.

- The API and related repos contain our search, explore, front-page, and other relevance algorithms that govern how content discovery works. While part of me would really like to release this info to the community it does present a fairly great risk of helping Scratchers “game” the algorithm and cheat the community.

- The API and related repos contain all of the information about how we automatically filter and moderate content. Sharing this information would make it easier for spammers and trolls to attack the community.

- This is a terrible reason: The API and related repos include some technology that MIT would prefer that we not disclose because they are interested in patenting it. This is a really bummer as I am strongly opposed to software patents of any kind, but until we resolve this issue we cannot even consider releasing the code.

I am a huge advocate of OSS (I was the Director of Research at the Mozilla Foundation before joining MIT) and have been pushing us to release more and more, but we have to balance the needs of the community. Hope that helps clarify!

- Andrew (thisandagain)", originally posted by @towerofnix [here](https://scratch.mit.edu/discuss/post/2701986/).

**Comment by R4356th** [comment]
Please close this issue as this is not relevant.

**Comment by R4356th** [comment]
What did you reopen this for?

**Comment by GrahamSH-LLK** [comment]
I don't think that's relevent for scratchr2.

**Comment by R4356th** [comment]
> 
> 
> I don't think that's relevent for scratchr2.

That is related.

**Comment by GrahamSH-LLK** [comment]
It's not backend, its frontend (at least partially.)

**Comment by R4356th** [comment]
> 
> 
> It's not backend, its frontend (at least partially.)

The particular quote is for the API.

**Comment by GrahamSH-LLK** [comment]
I'll just wait for someone on the ST. (Not that I don't beleive you, it's just that I want info on scratchr2 specifically.)

**Comment by R4356th** [comment]
"[scratchr2] is a big monolithic (and also now legacy) codebase that is very tightly tied to our old moderation systems as well as our infrastructure. Because of this, MIT was not comfortable granting us permission to open source the codebase. For everything new we work on, we try to have the code be much more modular which makes it much easier to open source / get approved by MIT's lawyers." - thisandagain once again, https://scratch.mit.edu/users/thisandagain/#comments-48878804, originally by @towerofnix [here](https://scratch.mit.edu/discuss/post/3249585/).
