### ISSUE TITLE
Do not use "million" placeholder

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#4590]
Some languages like Japanese don't have corresponding words for them in some cases.

Example:

- 1 million -> 100万 (can be cheated by translating "million" to `00万`, but gives Transifex warning)
- 100 million -> 1億 (errors because we can't use million placeholder, but Transifex requires it)
- 170 million -> 1億7000万

Please include the entire number, instead of using placeholders, or at least make it so that you can omit placeholders.

**Comment by Kenny2github** [comment]
Chinese translators I know handle this by using 百萬(tw)/百万(cn) as "million". It makes it a bit awkward because "100 million" → "100 百万" → "one hundred hundred myriad" but that's no less awkward than "thousand million million" to avoid the whole quadrillion/billiard confusion.

**Comment by chrisgarrity** [comment]
@apple502j @Kenny2github `{million}` is currently a placeholder in the [annual-report](https://scratch.mit.edu/annual-report) to allow for formatting in the reach section of the page. Here's the layout:
![Screen Shot 2020-11-05 at 2 24 17 PM](https://user-images.githubusercontent.com/399209/98286982-b9de0480-1f72-11eb-8230-12a74e3fece3.png)
Note, we cannot simply add the HTML formatting to the string as that feature is deprecated. We are not adding any new strings with embedded HTML.

Also note that simply leaving out the space in the translation is probably not doing what you expect:
![Screen Shot 2020-11-05 at 2 34 57 PM](https://user-images.githubusercontent.com/399209/98288011-32919080-1f74-11eb-8fbf-7e7ec07caca7.png)

Warnings are there to make sure you check for common mistakes. They can be ignored when the common mistake is not applicable.

**Comment by apple502j** [comment]
@chrisgarrity Warnings are fine, but if we didn't use placeholders at all, the translation doesn't seem to save.

**Comment by chrisgarrity** [comment]
@apple502j  correct, you cannot remove the placeholder, and we are not going to remove the placeholder because it allows us to format the content correctly. 

The suggestion is to translate [million](https://www.transifex.com/llk/scratch-website/translate/#ja/annual-report-l10njson/306569047) as 万, not 00万.
Then translate '170 {million}' as '1億7000 {million}' When formatted, '1億7000' would be the larger first line and '万' would be the second line.

However, this is really about how to translate the strings. The placeholder is in the code for a valid reason, so there's nothing to "fix" and I'm going to close the issue. Discussion of how to translate the placeholder can continue in transifex.
