### ISSUE TITLE
Classroom thumbnail is too big

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#4729]
scratchr2 issue. tl;dr: see https://scratch.mit.edu/classes/2/
related to CDN migration?

**Comment by mxmou** [comment]
https://uploads.scratch.mit.edu/classrooms/avatars/default.png is 300x223, but `scratchr2` expects a smaller image, so it sets width and height to auto. Could be fixed by changing height to 100%.

Another related issue is that https://uploads.scratch.mit.edu/users/avatars/default.png is now a 404.

**Comment by GrahamSH-LLK** [comment]
> Another related issue is that https://uploads.scratch.mit.edu/users/avatars/default.png is now a 404.

Moved to #4735

**Comment by lovecodeabc** [comment]
> https://uploads.scratch.mit.edu/classrooms/avatars/default.png is 300x223, but `scratchr2` expects a smaller image, so it sets width and height to auto. Could be fixed by changing height to 100%.
> 
> Another related issue is that https://uploads.scratch.mit.edu/users/avatars/default.png is now a 404.

Yeah, scratch is strange with the CDN issues

**Comment by BryceLTaylor** [comment]
One side effect of this issue is that the image completely covers the class name, which prevents users from changing the name of their classes.  

You can get around this by inspecting the element of the image and then hiding it.  That gives access to the text so you can change it, but is unreasonable to ask users to do.

**Comment by mxmou** [comment]
Seems fixed.
