### ISSUE TITLE
[Conference] Links on main page left-aligned on small browsers

### ISSUE THREAD

**Issue by technoboy10** [LLK/scratch-www#506]
On the staging site, the links below the title banner are left-aligned on browsers smaller than 640px in width. 

**Browsers**
(tested) Chrome 50.0.2661.89, Android 6.0.1
(tested) Vivaldi 1.1.453.59

<img width="200" alt="screenshot 2016-05-23 08 55 57" src="https://cloud.githubusercontent.com/assets/3019167/15471843/2304f29e-20c6-11e6-9312-cafc38a3b13c.png">

**Comment by mewtaylor** [comment]
closed in https://github.com/LLK/scratch-www/commit/b020964ef4e23bef0034d810b714e230fc3df9b7

**Comment by technoboy10** [comment]
Works as expected on Chrome 50, Firefox 46, and Safari 9.1 on OS X 10.11.5.

**Comment by jwzimmer** [comment]
@rschamp I was double-checking this since @technoboy10 tested this and also worked on the fix. I agree it's QA-OK. : )

Links below title banner are center-aligned in small screen/ resized browser on 
- my iPhone 6 (iOS) in Chrome
- Samsung tablet Eggs Benedict in Chrome (not center aligned but correctly aligned horizontally since the screen is big enough)
- Chrome Version 50.0.2661.102 (64-bit) on my Mac
- IE 11.0.9600.18314, VM for Win7 from microsoft

Resizing Chrome browser on Mac:
![out9](https://cloud.githubusercontent.com/assets/1320456/15614776/8ef3ccd8-2408-11e6-8358-e6d13ea73b7b.gif)
