### ISSUE TITLE
Change conference/2020 to conference/2021

### ISSUE THREAD

**Issue by zoebentley** [LLK/scratch-www#5197]
Currently, if you go to the URL "scratch.mit.edu/conference," you go to "scratch.mit.edu/conference/2020"

Desired behavior: 
1. We would like the contents of the page "scratch.mit.edu/conference/2020" to be at "scratch.mit.edu/conference/2021"
2. We would like "conference" to redirect to "conference/2021"
3. We would like "conference/2020" to redirect to "conference/2021" (in case people go to the old URL)

**Comment by carljbowman** [comment]
Just wanted to propose simplifying the URLs a bit, but there may be reasons to not do this.

One could imagine visiting `scratch.mit.edu/conferece` and that not redirecting to a URL with the year appended. I.e. `scratch.mit.edu/conferece` would always display the current conference information for that year.

Year to year, when we need make the change to display information for the next upcoming conference, we add the year to the associated URL for archival purposes, I.e.  A past year's content gets moved from `scratch.mit.edu/conference` to `scratch.mit.edu/conference/DATE`

It begs the question of if we want to archive 2020 in anyway, my guess is no since we would redirect 2020 to 2021 based on the proposal above.

**Comment by Accio1** [comment]
@carljbowman I'm not on the Scratch Team or anything but I think that your idea above is good. It makes sense that unless /conference was an overall information page for Scratch Conference in general, which would remain the same no matter which year it was, it should be the page for the current conference, as right now it is just kind of wasted on a redirect.

**Comment by CubeyTheCube** [comment]
Will /conference/2021 just not exist then? That might be a little counterintuitive for users who saw the link used to be /conference/2020

**Comment by wgyt** [comment]
> Will /conference/2021 just not exist then? That might be a little counterintuitive for users who saw the link used to be /conference/2020

I think that /conference/2021 should redirect to /conference/2021 in 2021, but not in 2022
