### ISSUE TITLE
"Embrace remix culture" section of Community Guidelines is misleading

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-www#5644]
From [this forum topic](https://scratch.mit.edu/discuss/topic/522609/).

The Community Guidelines say:
> You are encouraged to use anything you find on Scratch in your own creations, as long as you provide credit to everyone whose work you used and make a meaningful change to it.

This implies that you need to give credit and make a meaningful change every time you use someone else's work, which is not true. Giving credit is only necessary when you're using someone else's work as part of your project (if you're remixing it Scratch's automatic credit is enough), and making a meaningful change is only necessary if you're remixing a project (you're allowed to use another person's work as part of the project it can be unchanged). If this becomes a common misunderstanding (or if it already is) even more people will be complaining about art theft.

I think the sentence should be changed to
> You are encouraged to use anything you find on Scratch in your own creations, as long as you provide credit to everyone whose work you used, and *to remix any project if you* make a meaningful change to it.

**Comment by AmazingMech2418** [comment]
Well, giving credit includes the automatic credit from remixing (although, I personally think more should be required in the case that the original project is unshared, since then, any credit is removed) and also, a meaningful change includes only using something rather than just copying the project. A better way would be to say "and to make sure that your project contains some of your work and does not solely rely on other people's work" or something like that.

Personally, I think a more misleading part is in the "You are encouraged to use anything you find on Scratch in your own creations" part. Anything a Scratcher creates on Scratch is licensed by CC-BY-SA-2.0, but let's say someone has personally acquired rights to use a copyrighted piece of music. That music still follows under its original license and is not under CC-BY-SA-2.0, so another Scratcher using that in their projects might count as copyright infringement. Same goes with artwork as well. (no Scratch code can be licensed separately since it is made *in Scratch* and therefore follows under CC-BY-SA-2.0)

**Comment by BryceLTaylor** [comment]
Github is not the appropriate forum to discuss the Scratch community's policies.

**Comment by mxmou** [comment]
@BryceLTaylor Even if the discussion is about the text, not about the policy itself?

**Comment by Scratchfangs** [comment]
@BryceLTaylor He is talking about the text lol
