### ISSUE TITLE
HOC page formatting issue

### ISSUE THREAD

**Issue by leoburd** [LLK/scratch-www#572]
I've just noticed a formatting issue on the Hour of Code page (https://scratch.mit.edu/hoc). 

The activity cards and guides' names get all messed up whenever their size is too big for the column their in. Have a look at the images below. The problem seems to affect all languages.

In pt-br:
![20160608-hoc_formatting_issue](https://cloud.githubusercontent.com/assets/171118/16050178/a87d8d8c-3228-11e6-8869-208c7ec2e884.png)

In en:
![20160608-hoc_formatting_issue2-en](https://cloud.githubusercontent.com/assets/171118/16050176/a87d1c94-3228-11e6-976d-82238eee8d61.png)

Thanks!

**Comment by Choco31415** [comment]
I replicated the issue, and it seems it's happening because the css is forcing a line-height of 0 on the h5 headers. I'm not sure which file that is in, but the css is specifically targeting `.hoc .resource .resource-info h5`.

One other thing that I noticed is that the h5 becomes ~100 pixels narrower, forcing the new line. The new line seems unavoidable.

I attempted fixing this issue, with successful results in Google Chrome v51. I set line-height to inherit, so the h5 could span multiple lines. I removed the h5's margin, to fix header positioning.

I took some screenshots to show off the fix:

Here is the squished HOC page: http://u.cubeupload.com/Choco31415/e79ScreenShot20160614at.png

Here is the regular HOC page: http://u.cubeupload.com/Choco31415/d86ScreenShot20160614at.png

As you can see, this fix shifts the headers up 3 pixels, but that's not very significant. If it becomes bothersome, adding a `margin-top` to the h5 would help. Image: http://u.cubeupload.com/Choco31415/606ScreenShot20160614at.png

By the way, is it okay if I help debug like this? :)

**Comment by Choco31415** [comment]
I have confirmed that the fix works on Firefox and Chrome.
