### ISSUE TITLE
We link to My Classes in Educator FAQ which 403s if you are not signed in as a teacher

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#658]
It seems a bit awkward to me that we link to My Classes in the FAQ but if you are not signed in as a teacher (if you're logged out or logged in as not-a-teacher), that page will give you a 403 error.

/cc @kaschm 

<img width="959" alt="screen shot 2016-07-01 at 1 20 56 pm" src="https://cloud.githubusercontent.com/assets/1320456/16529123/13ea5a64-3f8f-11e6-86e8-bcd7f97884ad.png">
<img width="978" alt="screen shot 2016-07-01 at 1 20 47 pm" src="https://cloud.githubusercontent.com/assets/1320456/16529124/13eebf82-3f8f-11e6-8952-493f339045a2.png">

**Comment by kaschm** [comment]
Yes - let's just change the text and remove the link entirely:

Current:

What happens if a student forgets their password?
You can manually reset a student password from within your Scratch Teacher Account. First, navigate to My Classes. From there, find the correct Class and click on the Students link. You can then reset the password at the student level using the Settings menu.

New: 

What happens if a student forgets their password?
You can manually reset a student password from within your Scratch Teacher Account. First, navigate to My Classes (either from the purple banner on the homepage or in the dropdown menu next to your user icon). From there, find the correct Class and click on the Students link. You can then reset the password at the student level using the Settings menu.
