### ISSUE TITLE
Add Display Names to Scratch

### ISSUE THREAD

**Issue by AksharVivek** [LLK/scratch-www#6915]
Scratch should add display names, similar to roblox, so you can change names, but still know who the original username was so we will know who is who in scratch.

Do you agree??

**Comment by AksharVivek** [comment]
oh hi

**Comment by derter-menter** [comment]
Rejected:
8.1 [Changing usernames](https://scratch.mit.edu/discuss/topic/8664/?page=4#post-367229) or [changing display names](https://scratch.mit.edu/discuss/topic/240442/?page=1#post-2456140)
If a user could change their username (or even set a certain “nickname” or “display name”), this could be very confusing for the Scratch community, especially for those following that user.  In addition, this would make moderation of the website more difficult because it would be harder for the Scratch Team to keep an eye on what a user may be doing.  The Scratch Team has allowed username changes only on very rare occasions, such as if the username contained inappropriate content or personal information.  Generally, the Scratch Team does not change usernames on request (including for reasons such as “I do not like my current username anymore”).

However, because of the way that usernames are stored on the server, changing the cases of letters in your username.

Source: https://scratch.mit.edu/discuss/topic/343602/

**Comment by AksharVivek** [comment]
> Rejected: 8.1 [Changing usernames](https://scratch.mit.edu/discuss/topic/8664/?page=4#post-367229) or [changing display names](https://scratch.mit.edu/discuss/topic/240442/?page=1#post-2456140) If a user could change their username (or even set a certain “nickname” or “display name”), this could be very confusing for the Scratch community, especially for those following that user. In addition, this would make moderation of the website more difficult because it would be harder for the Scratch Team to keep an eye on what a user may be doing. The Scratch Team has allowed username changes only on very rare occasions, such as if the username contained inappropriate content or personal information. Generally, the Scratch Team does not change usernames on request (including for reasons such as “I do not like my current username anymore”).
> 
> However, because of the way that usernames are stored on the server, changing the cases of letters in your username.
> 
> Source: https://scratch.mit.edu/discuss/topic/343602/

what i mean is like there would be a thing below that says your original name

**Comment by derter-menter** [comment]
> > Rejected: 8.1 [Changing usernames](https://scratch.mit.edu/discuss/topic/8664/?page=4#post-367229) or [changing display names](https://scratch.mit.edu/discuss/topic/240442/?page=1#post-2456140) If a user could change their username (or even set a certain “nickname” or “display name”), this could be very confusing for the Scratch community, especially for those following that user. In addition, this would make moderation of the website more difficult because it would be harder for the Scratch Team to keep an eye on what a user may be doing. The Scratch Team has allowed username changes only on very rare occasions, such as if the username contained inappropriate content or personal information. Generally, the Scratch Team does not change usernames on request (including for reasons such as “I do not like my current username anymore”).
> > However, because of the way that usernames are stored on the server, changing the cases of letters in your username.
> > Source: https://scratch.mit.edu/discuss/topic/343602/
> 
> what i mean is like there would be a thing below that says your original name

still applies - this is rejected

**Comment by tomlum** [comment]
For now, like derter-menter mentioned, there are not plans for this feature, but we'll take note of your suggestion.
