### ISSUE TITLE
Logging in as new student from help page doesn't redirect me to student account registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#759]
Staging, Chrome. Re https://github.com/LLK/scratch-www/pull/744.

I did not go through all the scratch-www vs. scratchr2 pages... it's possible there are other pages that fail to redirect. Let me know if I should look for more in more detail. : )

- Created student2class1 (as teacher3830)
- Signed in from homepage, got redirected to complete_registration
- Signed in from discuss (forums), got redirected to complete_registration
8) I cleared cookies and logged in from the help page, and **was not redirected to complete_registration**:
<img width="926" alt="screen shot 2016-07-26 at 2 33 52 pm" src="https://cloud.githubusercontent.com/assets/1320456/17150618/1324c160-533e-11e6-8435-85740fab8a58.png">
- Signed in from homepage again, got redirected to complete_registration again

**Comment by rschamp** [comment]
This is due to the help page being cached, so the app doesn't have a chance to redirect you based on your account details. I think this is ok, since the student won't be able to do anything substantial on the site without hitting the reset password page. When the help page is moved over to scratch-www this issue will be resolved.
