### ISSUE TITLE
Update Wiki Footer Link to use User's Language

### ISSUE THREAD

**Issue by Choco31415** [LLK/scratch-www#815]
Currently, when a user clicks on the Scratch Wiki footer link, it takes them to the English wiki. This ignores the user's language. It would be nice if when a user clicks on the Scratch Wiki footer link, they are taken to the wiki of their language, if it exists.

**Comment by kaschm** [comment]
Moved to LLK/scratch-wiki#1

**Comment by chrisgarrity** [comment]
Re-opening this on www because generating the correct link in the footer is something that needs to be handled on the www side of things (not in the wiki). The current list of languages that have their own wiki is:
* German
* Russian
* Dutch (Nederlands)
* Indonesian
* Japanese
* Hungarian 
* French

If a language does not have it's own wiki it should default to the English one: 
https://en.scratch-wiki.info/

This will require a new  localized URL resource (the wiki link and the other languages available), and the build locales script would need to include it on every page since it's in the footer.

**Comment by Kenny2github** [comment]
Though it will happen rarely, what should the procedure be for when a new language is supported? Simply change the localized link for that language away from the enwiki link?

**Comment by apple502j** [comment]
Hmm, they mean this: https://github.com/LLK/scratch-www/blob/develop/bin/get-localized-urls
https://resources.scratch.mit.edu/localized-urls.json contains the links

**Comment by chrisgarrity** [comment]
https://resources.scratch.mit.edu/localized-urls.json is generated based on the actual translation files available on the resources server. I don't think there's any way to automate this new information, so yes, someone would have to manually update the links data when a new wiki is added.

**Comment by 439bananas** [comment]
My issue with this is that, there are some languages that the wiki isn't supported in, so those languages would return undefined.scratch-wiki.info

**Comment by BoomerScratch** [comment]
> My issue with this is that, there are some languages that the wiki isn't supported in, so those languages would return undefined.scratch-wiki.info

If the language isn't supported, the link should be test.scratch-wiki.info or scratch-wiki.info.

**Comment by R4356th** [comment]
@benjiwheeler, I could work on this, if you wanted to have this feature.

**Comment by benjiwheeler** [comment]
@R4356th Thanks, that would be great! I don't know how complex the solution will need to be, which is why I haven't labeled it Help wanted.

**Comment by apple502j** [comment]
@R4356th Please do not submit PRs (or at least mark it as draft) - I need to ask Scratch Wiki admins about the change.

**Comment by R4356th** [comment]
> @R4356th Please do not submit PRs (or at least mark it as draft) - I need to ask Scratch Wiki admins about the change.

@apple502j, done with that?
