### ISSUE TITLE
[microworlds] make "Open in Scratch" button work on www pages

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#818]
The "Open in Scratch" button for microworlds is working well embedded in pages on the old server but doesn't work yet on www pages. 

For example this works: https://scratch.mit.edu/pathways/hiphop/
But not this: https://scratch.mit.edu/projects/embed-editor/116297919/?isMicroworld=true

@mewtaylor @bsb20 @morantsur I think you've all discussed this, but thought to make a github issue so we can track it. Many participants in our workshop were excited about that they can create their own microworlds. Thanks!

**Comment by morantsur** [comment]
Adding @rschamp that was part of the offline discussion, and can probably add more details.

**Comment by rschamp** [comment]
The summary of our meeting was that this line causes an infinite loop when the embedded editor isn't running in an iframe because `window === parent` when not within an embedded iframe: https://github.com/LLK/scratchr2/blob/5ad84583df9d5d5d29b37bbfb87fbbf58a1fdcf2/static/js/apps/project/embed_editor.js#L61

If we fix that to instead use its own `getCookie` rather than using the parent iframe, then the embedded editor will be able to retrieve the csrf cookie on its own. The csrf token from the cookie will be valid since the embedded editor is served from the scratch.mit.edu host.  This should allow the embedded editor to perform the remix.  After it performs the remix, if `isMicroworld` and it's not running in an iframe, then redirect to the project detail page.
