### ISSUE TITLE
Post Deploy Mobile Issues 

### ISSUE THREAD

**Issue by St19Galla** [LLK/scratch-www#883]
First off, I'd like to begin by saying that this was a fantastic update! I love the redesigned search and especially the new explore page! However, I experienced some issues on my mobile device (iPhone 5s) due to the new responsive design (which is great by the way!). I'm dumping them all here instead of creating a bunch of individual issues - please let me know if you'd rather I do that. :)

1. About Scratch Page Video
<s>The video element doesn't seem to be responsive with the rest of the page creating a bad formatting issue with the background:</s> **Moved to: #891** 
<img src="https://cloud.githubusercontent.com/assets/16446551/17989366/c83e9732-6afa-11e6-8abd-bdc605741260.PNG" width=300px>

2. Footer Responsiveness 
<s>On multiple pages (ex: Developers, About, Terms of Use, etc.) the footer is not responsive with the rest of the page creating another background issue:</s> **Moved to: #892**
<img src="https://cloud.githubusercontent.com/assets/16446551/17989455/55a2d3b8-6afb-11e6-94cc-7ac1ee849522.PNG" width=300px> <img src="https://cloud.githubusercontent.com/assets/16446551/17989426/1eee3fa6-6afb-11e6-8b6c-59d8e1f662bc.PNG" width=300px>

3. Teacher Account Request
<s>On the Teacher Account Request page/form, the entry box is not responsive with the rest of the page causing yet another background issue:</s> **Moved to: #893**
<img src="https://cloud.githubusercontent.com/assets/16446551/17989488/aacd24ba-6afb-11e6-9a9e-326be4f1429e.PNG" width=300px>

4. Community Guidelines Image
<s>On the Community Guidelines page, the bottom image is not responsive in changing size with the rest of the page, causing (yep you guessed it :P) another background issue:</s> **Moved to: #894** 
<img src="https://cloud.githubusercontent.com/assets/16446551/17989512/d79cce28-6afb-11e6-8895-1d8cf66af848.PNG" width=300px>

5. Page Borders
<s>On multiple pages (ex: Terms of Use, Privacy Policy, etc.) there doesn't seem to be any border to the left of the text causing it to be hard to read - especially the numbered lists:</s> **Moved to: #895**
<img src="https://cloud.githubusercontent.com/assets/16446551/17989549/23f4bf24-6afc-11e6-8ec2-76799be7e4ca.PNG" width=300px>

6. General Suggestion
I found it a bit disappointing that I can no longer access important pages such as Explore, Discuss, Educators, Developers, etc. and even Search from the updated pages without manually typing them into the url. Perhaps having something along the lines of a [drop-down menu](http://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_js_dropdown_filter) might be something to consider? :)

All in all, great update! These were the only issues I can find, but I'll keep it updated if I find any more! :D Also, ignore the white square over the messages icon - that's a known bug with my phone.

**Comment by mewtaylor** [comment]
Thanks @St19Galla, this is very helpful! I do think that splitting each of these into their own issue would be helpful for tracking fixes, so if you have the time to do please go ahead and do that – if not, I'd be happy to split it up myself.

As for number 6 – the feedback is very helpful! I know @carljbowman gave the mobile nav a great deal of thought, and considered a number of possible paradigms, before we arrived on this particular design. @carljbowman would definitely would have a better perspective on that than I do. 

One consideration with the dropdown that at least came up for me when thinking about it – given that we currently have a dropdown in the nav bar (sign in/account navigation), it might be difficult to have that dropdown be part of another dropdown, meaning that we would have to reconsider how that content fits into the dropdown navigation paradigm.

**Comment by St19Galla** [comment]
@mewtaylor Moving them into separate issues now :)

Ah, that would be difficult. I forgot about the other drop-down nav bar :P

**Comment by carljbowman** [comment]
@St19Galla - Thanks for taking a look at all of these things across mobile!! Super awesome to see excitement around the site become responsive. This is something I deeply care about. We are working through a lot of different variants both on the technical side and design side to resolve some of these issues, but the migration takes time and iteration.

A lot of the issues that you found stem from issues with our grid systems, which we are planning to revamp. Currently we are in a prototypical phase with our grid. We are trying it on static pages in an attempt to balance all the types of content on Scratch and the many different screen sizes that can access that content. Things like the image on Community Guidelines do not scale with the grid such they break the page. Def keep an eye out and call out these issues!! Super helpful!!

Navigation is always a challenge when it comes to responsive behavior. The team spent a lot of time deciding which parts of the nav to hide and which to keep. Some of the underlying reasoning to hide things like Search and Explore is due to the inability to watch projects on Mobile Devices and the fact that the Project page is not responsive. I am very excited to explore (pun intended) the Project page, especially when it comes to commenting across devices. 

We are also thinking a lot about the overall information architecture of the site. Our goals of making content like the Developer and Educator pages easier to find and more accessible intersects with the work we are doing with responsive behavior. These are just the first steps. There is a lot more to consider and plenty of opportunity.

Thanks for calling these issues out and keeping us on our toes!

PS - Charge your phone. :P

**Comment by St19Galla** [comment]
@mewtaylor Done! :)

@carljbowman Hehe, I was wondering if someone would comment on that :P Anyway, no problem! I'm happy to help :) Really looking forward to see all the changes to come - and you're completely right, the Explore and Search feature doesn't really make sense for Mobile right now. I didn't even think of that :P Thanks for the update!

**Comment by mewtaylor** [comment]
@St19Galla also – feel free to close this issue once you've migrated these into their own issues!
