### ISSUE TITLE
Add more space in footer on Safari

### ISSUE THREAD

**Issue by coke11** [LLK/scratch-www#885]
I was looking at the footer in Safari. It has looked good the last couple of days, but I just noticed that today it looks like this in Safari
![footer](https://cloud.githubusercontent.com/assets/18141280/18004694/1fd4dd16-6b5b-11e6-98b3-7d5968c0d946.png)
Would it be possible to add some more spacing?

I also tested in Chrome and Firefox. This is what I got in Chrome
![screen shot 2016-08-26 at 7 00 45 am](https://cloud.githubusercontent.com/assets/18141280/18004704/36f22eae-6b5b-11e6-948f-c0fe5dceace6.png)
Seems fine in chrome. 

And here is what is happening in firefox
![screen shot 2016-08-26 at 7 01 38 am](https://cloud.githubusercontent.com/assets/18141280/18004717/4b9702e4-6b5b-11e6-9787-2587a509b51b.png)
It looks good other then the language bar. Should that be it's own issue?
Staging: Safari Version 8.0.5, Mac 10.10.3

**Comment by mewtaylor** [comment]
thanks @coke11 ! For the footer spacing – since this appears to be specific to Safari, would you mind mentioning that in the title for this issue? I also was unable to repro on Safari 9.1.2, OS X 10.11, so if you don't mind also including your OS version and browser version in the issue description, that'd be super helpful!

As for the language dropdown – we do have an issue for creating a new dropdown component ourselves (https://github.com/LLK/scratch-www/issues/593). I'm thinking that it might make sense to add a comment about what you're seeing in Firefox on that issue, perhaps?

**Comment by St19Galla** [comment]
Unable to repro on Safari 9.1.2 OS X 10.10.5
Perhaps it's an issue with the older Safari version? :)
