### ISSUE TITLE
Create "Things to Try" page

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#979]
New page that will contains resources such as tutorials, educator guides and activity cards for getting started with Scratch.

Components this will need:
- `TitleBanner`
- Resource Tile (new component)
- Resource Modal (new component) (see #980)

**Comment by carljbowman** [comment]
## Things to Try page - Responsive Behavior

### Desktop - 12col
* The vertical size of resource tiles will vary. This variation can be more dramatic based on translation. So rather than setting a fix char length or hiding overflown content, we should use a 'masonry' grid and allow for tiles to paginate asymmetrically

![r2 0_thing-to-try 12col](https://cloud.githubusercontent.com/assets/3409578/19690566/1db1b5a4-9a9f-11e6-9d56-672f9a24c9ab.png)

![r2 0_thing-to-try 12col-grid](https://cloud.githubusercontent.com/assets/3409578/19690547/1142239e-9a9f-11e6-8d58-87d0efd5d9e4.png)

### Tablet to Desktop - 8col
![r2 0_thing-to-try 8col](https://cloud.githubusercontent.com/assets/3409578/19691216/7e37923e-9aa1-11e6-9691-51dbdfa5a7de.png)

![r2 0_thing-to-try 8col-grid](https://cloud.githubusercontent.com/assets/3409578/19691220/80a88028-9aa1-11e6-95cc-59f538e08fe9.png)

### Mobile to Tablet - 6col
_A perfect example of where our current fixed grid system could use some tweaking. Lots of unused space. A flexible grid could help fill the space across more devices, but we would need to design with more variation in mind_

![r2 0_thing-to-try 6col](https://cloud.githubusercontent.com/assets/3409578/19691879/d8f7c7d2-9aa3-11e6-80a0-b6929c230416.png)

![r2 0_thing-to-try 6col-grid](https://cloud.githubusercontent.com/assets/3409578/19691880/db39ffa6-9aa3-11e6-986a-0d4e6d39bda1.png)


### Mobile - 4col
![r2 0_thing-to-try 4col](https://cloud.githubusercontent.com/assets/3409578/19692425/e18cc440-9aa5-11e6-87ac-60a7c6243f30.png)

![r2 0_thing-to-try 4col-grid](https://cloud.githubusercontent.com/assets/3409578/19692431/e9365f6c-9aa5-11e6-9c2e-494464010fc1.png)

## 'See Cards & Guides' Modal - Responsive Behavior

Generally I have some concerns about scrolling paradigms with in modals. On smaller devices as the content will grow beyond the length of the screen the user will need to be able to scroll the modal rather than the page. Flagging in case we need to adapt the design to account for this behavior.

### Desktop - 12col
![r2 0_things-to-try 12col](https://cloud.githubusercontent.com/assets/3409578/19693128/72cbce5e-9aa8-11e6-958f-147d25e0fab8.png)

![r2 0_things-to-try 12col-grid](https://cloud.githubusercontent.com/assets/3409578/19693131/75121efc-9aa8-11e6-9c17-d816b8b1f09f.png)

### Tablet to Desktop - 8col
![r2 0_thing-to-try 8col](https://cloud.githubusercontent.com/assets/3409578/19693704/74cb3382-9aaa-11e6-92c6-9c7612759425.png)

![r2 0_thing-to-try 8col-grid](https://cloud.githubusercontent.com/assets/3409578/19693710/778a3442-9aaa-11e6-8464-97a9d756b366.png)


### Mobile to Tablet - 6col
* Ideally the the modal would take up the entire screen and an example where scrolling gets tricky as mentioned above.
* Close may need to be more visible and should become fixed as to follow the user scrolls. This way they have the ability to close the dialog at any point regardless of where they are on the page.

![r2 0_thing-to-try 6col](https://cloud.githubusercontent.com/assets/3409578/19694043/c7af2c38-9aab-11e6-8133-923381da5bb6.png)

![r2 0_thing-to-try 6col-grid](https://cloud.githubusercontent.com/assets/3409578/19694058/d5a7fd6a-9aab-11e6-8196-a01172fa33aa.png)

### Mobile - 4col
![r2 0_thing-to-try 4col](https://cloud.githubusercontent.com/assets/3409578/19695053/b07ee5ae-9aaf-11e6-84a1-9c9529204bf2.png)

![r2 0_thing-to-try 4col-grid](https://cloud.githubusercontent.com/assets/3409578/19695055/b3c8e7f0-9aaf-11e6-87d2-31e00ee6416d.png)

**Comment by carljbowman** [comment]
@chrisgarrity - I will follow up with more detailed specs for the tiles & modals soon, as well as giving you the image assets and icons. Just wanted to get something up in the mean time.

**Comment by chrisgarrity** [comment]
@carljbowman Thanks for the head's up!

**Comment by thisandagain** [comment]
This looks great. Thanks for specs @carljbowman . 😄 👌

**Comment by mewtaylor** [comment]
@carljbowman quick question – for the banner images on the modal, are they going to be different from the ones on the resource tile/card/ethereal feeling component, or is it just an uncropped version of that image?

**Comment by carljbowman** [comment]
@mewtaylor - The banner image will be a different asset. Each resource tile will have two assets, one that will display on the tile and another for the banner image in the modal.

**Comment by kaschm** [comment]
*Text for top of page*

- You can get started with Scratch in a variety of ways. Click a picture to try a **Tutorial**. You can also download a set of **Activity Cards** and **Educator Guide** for each theme. 

*Titles, Descriptors:* 

Make It Fly 
Animate the Scratch Cat, The Powerpuff Girls, or even a taco! 

Animate Your Name
Animate the letters of your name, initials, or favorite word. 

Race to the Finish 
Make a game where two characters race each other. 

Make Music
Choose instruments, add sounds, and press keys to play music. 

Hide and Seek 
Make a hide-and-seek game with characters that appear and disappear. 

Create a Story 
Choose characters, add conversation, and bring your story to life. 

Fashion Game
Dress up a character with different clothes and styles. 

Pong Game 
Make a bouncing ball game with sounds, points, and other effects. 

Let's Dance
Design an animated dance scene with music and dance moves. 

Catch Game
Make a game where you catch things falling from the sky. 

Virtual Pet 
Create an interactive pet that can eat, drink, and play.

**Comment by kaschm** [comment]
From web meeting 11/3: url for page will be at **/try**

/cc @ntlrsk for comments or concerns?

**Comment by ntlrsk** [comment]
Just talked to Mres and we both thing that sounds like a temporary test page. 
I'd suggest: /**go**
Will run by a couple others to confirm.

**Comment by ntlrsk** [comment]
http://es.memegenerator.net/instance/46317245

**Comment by ntlrsk** [comment]
OK I talked with others and they suggested /**do**
(as Yoda says) (Note: Another concern raised with /**try** was that it may sound like a trial version that you have to pay for later.)

**Comment by ntlrsk** [comment]
Talked further with mres and he says /**go** sounds better than do.

**Comment by carljbowman** [comment]
@chrisgarrity - Added the images to @kaschm 's content https://github.com/LLK/scratch-www/issues/979#issuecomment-257947919

**Comment by kaschm** [comment]
@chrisgarrity @mewtaylor just checked with @ntlrsk and the ordering of the page should follow the cards page (/info/cards). The top row should highlight the same three (in the same order) as the homepage. thanks!

**Comment by chrisgarrity** [comment]
Just to clarify...
The first row should be Make It Fly, Animate Your Name, Make Music as shown in the mocks above...
Not
Animate Your Name, Make It Fly, Race to the Finish as shown on /info/cards

**Comment by ntlrsk** [comment]
@chrisgarrity I think Animate Your Name should come first. @carljbowman The thumbnails look great! (Finished pong game has red line across near bottom, but I think it's fine not to have it in the thumbnail.)

**Comment by ntlrsk** [comment]
To clarify, the order that @kaschm listed the 11 activities above with the thumbnails seems good to me (at least for the HOC period) - @chrisgarrity @carljbowman  Does that seem OK?

**Comment by chrisgarrity** [comment]
@ntlrsk Sounds fine. I'll get the correct order implemented with images :)

**Comment by chrisgarrity** [comment]
@ntlrsk @kaschm Should we be using the current PDFs for the activity cards, or are there new ones? Do we have copies of the guides that can be added?

**Comment by kaschm** [comment]
@chrisgarrity: good questions. I believe we can use the cards found on /cards. However, there are new versions of the Guides that aren't yet done. @ntlrsk can confirm ...

**Comment by ntlrsk** [comment]
The cards on the Cards page are the latest. The guides are all being revised right now, getting as many as possible for the Nov. 14 freeze!

**Comment by chrisgarrity** [comment]
@ntlrsk What are all the links that the tutorials should go to?
I know they all start `https://scratch.mit.edu/projects/editor/?tip_bar=`, but what's the tip bar parameter for each of them?

**Comment by ntlrsk** [comment]
name
fly
music
racegame
hide
[story - not available yet - so don't include]
[fashion - not available yet - so don't include]
pong
dance
catch
pet
Thanks!

**Comment by chrisgarrity** [comment]
@ntlrsk Thanks. Will story and fashion be available on Monday for the freeze? If not I'll take them out of the list.

**Comment by ntlrsk** [comment]
No they won't be. Thanks. ⁣​
